-- MySQL Script generated by MySQL Workbench
-- Wed Sep 23 10:38:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delilah-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delilah-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delilah-db` DEFAULT CHARACTER SET utf8 ;
USE `delilah-db` ;

-- -----------------------------------------------------
-- Table `delilah-db`.`ESTADOS_PO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah-db`.`ESTADOS_PO` (
  `ID_ESTADO` INT(11) NOT NULL,
  `ESTADO` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID_ESTADO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `delilah-db`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah-db`.`PEDIDOS` (
  `ESTADO` VARCHAR(20) NOT NULL,
  `HORA_FECHA` VARCHAR(100) NOT NULL,
  `ID_PO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_PROD` VARCHAR(100) NOT NULL,
  `TOTAL` VARCHAR(30) NOT NULL,
  `USUARIO` VARCHAR(16) NOT NULL,
  `DIRECCION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_PO`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `delilah-db`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah-db`.`PRODUCTOS` (
  `ID_PROD` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  `DISPONIBLE` VARCHAR(3) NOT NULL,
  `PRECIO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_PROD`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `delilah-db`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delilah-db`.`USER` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIO` VARCHAR(16) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `HASH` VARCHAR(100) NOT NULL,
  `FULL_NAME` VARCHAR(255) NOT NULL,
  `TELEFONO` VARCHAR(45) NOT NULL,
  `ISADMIN` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
