-- MySQL Script generated by MySQL Workbench
-- Sun May 24 18:11:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delilah-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `delilah-db` ;

-- -----------------------------------------------------
-- Schema delilah-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delilah-db` DEFAULT CHARACTER SET utf8 ;
USE `delilah-db` ;

-- -----------------------------------------------------
-- Table `delilah-db`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah-db`.`USER` ;

CREATE TABLE IF NOT EXISTS `delilah-db`.`USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(16) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(32) NOT NULL,
  `FULL_NAME` VARCHAR(255) NOT NULL,
  `TELEFONO` VARCHAR(45) NOT NULL,
  `DIRECCION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah-db`.`ESTADOS_PO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah-db`.`ESTADOS_PO` ;

CREATE TABLE IF NOT EXISTS `delilah-db`.`ESTADOS_PO` (
  `ID_ESTADO` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID_ESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah-db`.`FORMA_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah-db`.`FORMA_PAGO` ;

CREATE TABLE IF NOT EXISTS `delilah-db`.`FORMA_PAGO` (
  `ID_PAGO` INT NOT NULL AUTO_INCREMENT,
  `CONCEPTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_PAGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah-db`.`PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah-db`.`PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `delilah-db`.`PRODUCTOS` (
  `ID_PROD` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah-db`.`PEDIDOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah-db`.`PEDIDOS` ;

CREATE TABLE IF NOT EXISTS `delilah-db`.`PEDIDOS` (
  `ID_ESTADO` INT NOT NULL,
  `HORA_FECHA` VARCHAR(45) NOT NULL,
  `ID_PO` INT NOT NULL AUTO_INCREMENT,
  `ID_PROD` INT NOT NULL,
  `ID_PAGO` INT NOT NULL,
  `TOTAL` DECIMAL(1) NOT NULL,
  `USER_ID` INT NOT NULL,
  `DIRECCION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_PO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
